services:
  ollama:
    image: ghcr.io/wazeerc/nao.ai-ollama:latest
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - data:/root/.ollama
    environment:
      - NUXT_PUBLIC_OLLAMA_MODEL=${NUXT_PUBLIC_OLLAMA_MODEL}
      - NUXT_PUBLIC_EMBEDDING_MODEL=${NUXT_PUBLIC_EMBEDDING_MODEL}

  nao-ai:
    image: ghcr.io/wazeerc/nao.ai-app:latest
    container_name: nao-ai-ui
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - ollama
    environment:
      - NUXT_PUBLIC_OLLAMA_MODEL=${NUXT_PUBLIC_OLLAMA_MODEL}
      - NUXT_PUBLIC_EMBEDDING_MODEL=${NUXT_PUBLIC_EMBEDDING_MODEL}
      - NUXT_PUBLIC_OLLAMA_URL=${NUXT_PUBLIC_OLLAMA_URL}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}

volumes:
  data:
