services:
  ollama:
    build:
      context: .
      dockerfile: dockerfile.ollama
    image: "ollama"
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - data:/root/.ollama
    environment:
      - LLAMA_MODEL=${LLAMA_MODEL}

  myllama:
    build: .
    image: "myllama"
    container_name: myllama-ui
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434/
      - NUXT_PUBLIC_LLAMA_MODEL=${LLAMA_MODEL}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}

volumes:
  data:
